### ISSUE TITLE
[feat] Module options Component

### ISSUE THREAD

**Issue by AreYouIvan** [C10-Ghibli-s/FE-Backoffice#8]
### Summary
We will create a 'Module Options Component' which gets the category selected by the user in the 'Modules' view and renders the name of the category and two personalize links, one to 'Search and Edit' and the other one to 'Create a new' item. 

### Acceptance Criteria

- [x] Create the component 
- [x] Get the category selected by the user
- [x] Render the personalize names: Image: Replace by the category image. Title: Name of the category. First Link: Search and Edit + [Name of the category in plural form]. Second Link: Create a new + [Name of the category in singular form]. Create the route in the links depending on the category.
- [x] Test the component

**Comment by LilianaRestrepoTorres** [comment]
These were already implemented on PR #18 and PR#24.
